### PR TITLE
further handling of missing comm.kernel

### LINKED ISSUE #210: 'NoneType' object has no attribute 'session'  4.5.1
Going from ipykernel 4.5.0 to 4.5.1 we get the following error. The error only appears at the end of the execution of a script so luckily it doesn't affect our calculations. But it breaks our testing as travis thinks that it's our tests failing.

```pytb
Exception ignored in: <bound method Widget.__del__ of <ipywidgets.widgets.widget_layout.Layout object at 0x7f679e5e8d30>>
Traceback (most recent call last):
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 188, in __del__
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 238, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 109, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 65, in _publish_msg
AttributeError: 'NoneType' object has no attribute 'session'
Exception ignored in: <bound method Widget.__del__ of <ipywidgets.widgets.widget_box.Box object at 0x7f679e5e8278>>
Traceback (most recent call last):
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 188, in __del__
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 238, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 109, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 65, in _publish_msg
AttributeError: 'NoneType' object has no attribute 'session'
```

### PR DESCRIPTION
**Pull request by minrk**
- don't mark comm as open if it has no kernel
- don't send close message when kernel is None,
  which can happen during interpreter cleanup

closes #210, which appears to have been caused by #205

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Sorry for the oversight. This looks good to me.

**Comment by minrk** [comment]
No problem, I'll cut 4.5.2 with this (#212)
