### ISSUE TITLE
'NoneType' object has no attribute 'session'  4.5.1

### ISSUE THREAD

**Issue by stefdoerr** [ipython/ipykernel#210]
Going from ipykernel 4.5.0 to 4.5.1 we get the following error. The error only appears at the end of the execution of a script so luckily it doesn't affect our calculations. But it breaks our testing as travis thinks that it's our tests failing.

```pytb
Exception ignored in: <bound method Widget.__del__ of <ipywidgets.widgets.widget_layout.Layout object at 0x7f679e5e8d30>>
Traceback (most recent call last):
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 188, in __del__
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 238, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 109, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 65, in _publish_msg
AttributeError: 'NoneType' object has no attribute 'session'
Exception ignored in: <bound method Widget.__del__ of <ipywidgets.widgets.widget_box.Box object at 0x7f679e5e8278>>
Traceback (most recent call last):
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 188, in __del__
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 238, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 109, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 65, in _publish_msg
AttributeError: 'NoneType' object has no attribute 'session'
```

**Comment by minrk** [comment]
@stefdoerr thanks for the report. What tests, per chance?

@SylvainCorlay looks like this was caused by #205.

**Comment by stefdoerr** [comment]
Anything really. Just importing my software (HTMD) gives the error:

```pytb
[sdoerr@loro htmdacellera]$ cat test.py
if __name__ == '__main__':
    import htmd

[sdoerr@loro htmdacellera]$ python test.py 

Please cite -- HTMD: High-Throughput Molecular Dynamics for Molecular Discovery
J. Chem. Theory Comput., 2016, 12 (4), pp 1845-1852. 
http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00049

You are on the latest HTMD version (unpackaged : /shared/sdoerr/Work/htmdacellera/htmd).

Exception ignored in: <bound method Widget.__del__ of <ipywidgets.widgets.widget_box.Box object at 0x7f1a3d6b7a90>>
Traceback (most recent call last):
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 188, in __del__
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 238, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 109, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 65, in _publish_msg
AttributeError: 'NoneType' object has no attribute 'session'
Exception ignored in: <bound method Widget.__del__ of <ipywidgets.widgets.widget_layout.Layout object at 0x7f1a3cf76470>>
Traceback (most recent call last):
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 188, in __del__
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 238, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 109, in close
  File "/shared/lab/software/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py", line 65, in _publish_msg
AttributeError: 'NoneType' object has no attribute 'session'
```

**Comment by minrk** [comment]
Thanks, I verified that #211 fixes this. I also tracked down the culprit as [this check](https://github.com/marscher/progress_reporter/blob/v1.2/progress_reporter/bar/gui.py#L55), where progress_reporter is attempting to instantiate a `Box()` widget to guess if a notebook is in use, but this is not a valid check. ipykernel 4.5.1 fixes the bug that prevents this instantiation, causing progress_reporter to incorrectly return True for `__attached_to_ipy_notebook` as long as ipywidgets is installed.

A better fix in progress_reporter would be to check:

1. is IPython instantiated
2. is it a 'kernel'

which would be:

```python
from IPython import get_ipython
ip = get_ipython()
if ip is None:
    return False
if not getattr(ip, 'kernel', None):
    return False
# No further checks are feasible
return True
```

There's no feasible way to check if widgets are available in the frontend (in part because there can be multiple frontends, with mixed capabilities).

**Comment by stefdoerr** [comment]
Calling in @marscher

**Comment by stefdoerr** [comment]
Thanks a lot @minrk for finding the issue!

**Comment by marscher** [comment]
Thanks I'll prepare a fix in progress_reporter

**Comment by minrk** [comment]
4.5.2 release is on its way with this fix.

**Comment by francisco-dlp** [comment]
At HyperSpy [we still get this error with 4.5.2](https://circleci.com/gh/conda-forge/hyperspy-feedstock/31?utm_campaign=build-failed&utm_medium=email&utm_source=notification) (and 4.5.1). 4.5 works fine for us.

```
======================================================================
ERROR: hyperspy.tests.model.test_model.TestModel1D.test_notebook_interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/hyperspy/tests/model/test_model.py", line 324, in test_notebook_interactions
    m[0].notebook_interaction()
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/hyperspy/component.py", line 1212, in notebook_interaction
    container = VBox([active])
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipywidgets/widgets/widget_box.py", line 84, in VBox
    box.layout.display = 'flex'
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/traitlets/traitlets.py", line 583, in __set__
    self.set(obj, value)
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/traitlets/traitlets.py", line 572, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/traitlets/traitlets.py", line 1137, in _notify_trait
    type='change',
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipywidgets/widgets/widget.py", line 367, in notify_change
    self.send_state(key=name)
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipywidgets/widgets/widget.py", line 263, in send_state
    self._send(msg, buffers=buffers)
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipywidgets/widgets/widget.py", line 487, in _send
    self.comm.send(data=msg, buffers=buffers)
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipykernel/comm/comm.py", line 121, in send
    data=data, metadata=metadata, buffers=buffers,
  File "/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipykernel/comm/comm.py", line 66, in _publish_msg
    self.kernel.session.send(self.kernel.iopub_socket, msg_type,
nose.proxy.AttributeError: 'NoneType' object has no attribute 'session'
-------------------- >> begin captured stdout << ---------------------
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/IPython/core/formatters.py in __call__(self, obj)
    880             method = get_real_method(obj, self.print_method)
    881             if method is not None:
--> 882                 method()
    883                 return True
    884 

/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipywidgets/widgets/widget.py in _ipython_display_(self, **kwargs)
    480                 loud_error('The installed widget Javascript is the wrong version.')
    481 
--> 482             self._send({"method": "display"})
    483             self._handle_displayed(**kwargs)
    484 

/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipywidgets/widgets/widget.py in _send(self, msg, buffers)
    485     def _send(self, msg, buffers=None):
    486         """Sends a message to the model in the front-end."""
--> 487         self.comm.send(data=msg, buffers=buffers)
    488 
    489 

/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipykernel/comm/comm.py in send(self, data, metadata, buffers)
    119         """Send a message to the frontend-side version of this comm"""
    120         self._publish_msg('comm_msg',
--> 121             data=data, metadata=metadata, buffers=buffers,
    122         )
    123 

/feedstock_root/build_artefacts/recipe_root_1484048848760/_t_env/lib/python3.4/site-packages/ipykernel/comm/comm.py in _publish_msg(self, msg_type, data, metadata, buffers, **keys)
     64         metadata = {} if metadata is None else metadata
     65         content = json_clean(dict(data=data, comm_id=self.comm_id, **keys))
---> 66         self.kernel.session.send(self.kernel.iopub_socket, msg_type,
     67             content,
     68             metadata=json_clean(metadata),

AttributeError: 'NoneType' object has no attribute 'session'
<ipywidgets.widgets.widget_selectioncontainer.Accordion at 0x7f89a7d4f710>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
traitlets: WARNING: Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1279 tests in 329.185s

FAILED (SKIP=1, errors=1)
TESTS FAILED: hyperspy-1.1.1-py34_1
```

**Comment by francisco-dlp** [comment]
I've just noticed after reading through the thread that the error seems to be a feature and that we need to fix the test on our side. Sorry for the noise.
