### ISSUE TITLE
matplotlib inline backend broken after ipython display refactor

### ISSUE THREAD

**Issue by astromancer** [ipython/ipykernel#508]
The `%matplotlib inline` magic no longer works due with the latest ipython master since https://github.com/ipython/ipython/pull/12239

Leads to:
`ImportError: cannot import name 'display'`

The offending line is here: 
https://github.com/ipython/ipykernel/blob/7b7046adb9230bfdfc59fd332ae1647cdd521e3c/ipykernel/pylab/backend_inline.py#L18
