### ISSUE TITLE
Import of matplotlib.pyplot fails on Python 2

### ISSUE THREAD

**Issue by xflr6** [ipython/ipykernel#173]
After upgrading from `4.3.1` to `4.4.0` under Win7 (same in `jupyter notebook`):

```python
C:\Users\User>jupyter console
Jupyter console 5.0.0

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (
MD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.



In [1]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f467123fe04> in <module>()

(...)

c:\program files\python27\lib\site-packages\ipykernel\pylab\backend_inline.py in
_enable_matplotlib_integration()
    152     backend = get_backend()
    153     if ip and backend == 'module://%s' % __name__:
--> 154         configure_inline_support(ip, backend)
    155
    156 _enable_matplotlib_integration()

c:\program files\python27\lib\site-packages\IPython\core\pylabtools.pyc in confi
ure_inline_support(shell, backend)
    359     except ImportError:
    360         return
--> 361     from matplotlib import pyplot
    362
    363     cfg = InlineBackend.instance(parent=shell)

ImportError: cannot import name pyplot
```

**Comment by takluyver** [comment]
Rats - @minrk, I think it's a circular import bug, introduced by #159. Is there anything smart we can do, or should we just catch ImportError there and skip setting our custom rcparams?

**Comment by minrk** [comment]
on it. @xflr6 what version of matplotlib?

**Comment by xflr6** [comment]
`matplotlib: 1.5.2`

**Comment by minrk** [comment]
It apparently only affects Python 2, because Python 3's import changes handle this appropriately. I've got a couple of small fixes coming that we can push out quickly, and then I'd like to try to move most of the inline figure configuration out of core IPython and into ipykernel.

**Comment by minrk** [comment]
Released 4.4.1 with the fix
