### ISSUE TITLE
cell_id unexpected argument in a notebook extension.

### ISSUE THREAD

**Issue by PBrockmann** [ipython/ipykernel#972]
Hi, 

I have updated python to 3.9.13 and then my IPython notebook extension does not work anymore.
I get this error

```
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
TypeError: run_cell_new() got an unexpected keyword argument 'cell_id'
```

Any idea what I should adapt to get it operationnal again ?
I have inspected the ipkernel.py code and have noticed that a cell_id argument has been set by default to None.
That should be enough to insure backward compatibility, but it seems not ?

The code is available from:
https://github.com/PBrockmann/ipython_ferretmagic/blob/master/ferretmagic/ferretmagic.py

Issue described in https://github.com/PBrockmann/ipython_ferretmagic/issues/12

**Comment by PBrockmann** [comment]
My ferret juyter extension works with 6.9.2 release of ipykernel

**Comment by PBrockmann** [comment]
Fixed by adding ```cell_id=None``` in the run_cell function.
https://github.com/PBrockmann/ipython_ferretmagic/issues/12 closed.
